openapi: 3.0.3
info:
  title: Recursive API
  version: 1.0.0
paths:
  /users:
    post:
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
components:
  schemas:
    User:
      description: info.
    Address:
      properties:
        city:
          $ref: "#/components/schemas/Address"
# having required city produces invalid recursive structs.
#      required:
#        - city
