// Code generated by oapi-codegen. DO NOT EDIT.

package circularproperties

import (
	"github.com/go-playground/validator/v10"
)

type PostUsersResponse struct {
	City *Address `json:"city,omitempty"`
}

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

// User info.
type User = any

type Address struct {
	City *Address `json:"city,omitempty"`
}

func (a Address) Validate() error {
	return schemaTypesValidate.Struct(a)
}
