// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"time"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type CreateUserBody struct {
	// ID Auto-generated user ID
	ID    *string `json:"id,omitempty"`
	Name  string  `json:"name" validate:"required"`
	Email string  `json:"email" validate:"required"`

	// CreatedAt Auto-generated timestamp
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

func (c CreateUserBody) Validate() error {
	if err := bodyTypesValidate.Struct(c); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

type CreateUserResponse struct {
	// ID Auto-generated user ID
	ID    string `json:"id" validate:"required"`
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required"`

	// CreatedAt Auto-generated timestamp
	CreatedAt time.Time `json:"createdAt" validate:"required"`
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type User struct {
	// ID Auto-generated user ID
	ID    string `json:"id" validate:"required"`
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required"`

	// CreatedAt Auto-generated timestamp
	CreatedAt time.Time `json:"createdAt" validate:"required"`
}

func (u User) Validate() error {
	if err := schemaTypesValidate.Struct(u); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}
