// Code generated by oapi-codegen. DO NOT EDIT.

package xgotype

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
	googleuuid "github.com/google/uuid"
)

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Client struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

func (c Client) Validate() error {
	return schemaTypesValidate.Struct(c)
}

type ClientWithExtension struct {
	Name googleuuid.UUID `json:"name" validate:"required"`
	ID   *int64          `json:"id,omitempty"`
}

func (c ClientWithExtension) Validate() error {
	if v, ok := any(c.Name).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			return runtime.NewValidationErrorFromError("Name", err)
		}
	}
	return nil
}
