// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var pathTypesValidate *validator.Validate

func init() {
	pathTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(pathTypesValidate)
}

type GetNodesIDPath struct {
	// ID The ID of the node
	ID int `json:"id" validate:"required"`
}

func (g GetNodesIDPath) Validate() error {
	if err := pathTypesValidate.Struct(g); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

type GetNodesIDResponse struct {
	ID       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Children []Node  `json:"children,omitempty"`
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Node struct {
	ID       *int    `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Children []Node  `json:"children,omitempty"`
}
