// Code generated by oapi-codegen. DO NOT EDIT.

package xgotypename

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Client struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

func (c Client) Validate() error {
	if err := schemaTypesValidate.Struct(c); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

type ClientWithExtension = ClientRenamedByExtension

type ClientRenamedByExtension struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

func (c ClientRenamedByExtension) Validate() error {
	if err := schemaTypesValidate.Struct(c); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}
