// Code generated by oapi-codegen. DO NOT EDIT.

package customclienttype

import (
	"github.com/go-playground/validator/v10"
)

var clientOptionsValidate = validator.New(validator.WithRequiredStructEnabled())
