// Code generated by oapi-codegen. DO NOT EDIT.

package globalparams

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var queryTypesValidate *validator.Validate

func init() {
	queryTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(queryTypesValidate)
}

type GetItemsQuery struct {
	// Filter Filter items (first definition - string)
	Filter *string `json:"filter,omitempty"`
}

type CreateItemQuery struct {
	// Filter Filter items (first definition - string)
	Filter *string `json:"filter,omitempty"`
}

type GetItemsResponse struct {
	Items []string `json:"items,omitempty"`
}
