// Code generated by oapi-codegen. DO NOT EDIT.

package autoprefixed

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ProductVariations string

const (
	ProductVariationsA ProductVariations = "A"
	ProductVariationsB ProductVariations = "B"
	ProductVariationsC ProductVariations = "C"
)

// validProductVariationsValues is a map of valid values for ProductVariations
var validProductVariationsValues = map[ProductVariations]bool{
	ProductVariationsA: true,
	ProductVariationsB: true,
	ProductVariationsC: true,
}

// Validate checks if the ProductVariations value is valid
func (p ProductVariations) Validate() error {
	if !validProductVariationsValues[p] {
		return runtime.NewValidationError("", fmt.Sprintf("invalid ProductVariations value: %v", p))
	}
	return nil
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Product struct {
	Variations *ProductVariations `json:"variations,omitempty"`
}

func (p Product) Validate() error {
	if p.Variations != nil {
		if v, ok := any(p.Variations).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Variations", err)
			}
		}
	}
	return nil
}

type A = bool
