openapi: 3.0.0
info:
  title: Boolean Validation Test - Nested
  version: 1.0.0
paths:
  /billing/portal/configurations/{configuration}:
    post:
      operationId: postBillingPortalConfigurationsConfiguration
      summary: Test nested boolean validation
      parameters:
        - name: configuration
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - features
                properties:
                  features:
                    $ref: '#/components/schemas/PortalFeatures'

components:
  schemas:
    PortalFeatures:
      type: object
      required:
        - invoice_history
      properties:
        id:
          type: string
        invoice_history:
          $ref: '#/components/schemas/PortalInvoiceList'
    
    PortalInvoiceList:
      type: object
      required:
        - enabled
      properties:
        enabled:
          type: boolean
          description: Whether invoice history is enabled

