// Code generated by oapi-codegen. DO NOT EDIT.

package namingconflict2

type SourceType string

const (
	SourceTypeACHCreditTransfer SourceType = "ach_credit_transfer"
	SourceTypeAlipay2           SourceType = "alipay"
)

// All returns all possible values for SourceType.
func (s SourceType) All() []SourceType {
	return []SourceType{
		SourceTypeACHCreditTransfer,
		SourceTypeAlipay2,
	}
}

type PaymentSourceType string

const (
	PaymentSourceTypeACHCreditTransfer PaymentSourceType = "ach_credit_transfer"
	PaymentSourceTypeAlipay            PaymentSourceType = "alipay"
)

// All returns all possible values for PaymentSourceType.
func (p PaymentSourceType) All() []PaymentSourceType {
	return []PaymentSourceType{
		PaymentSourceTypeACHCreditTransfer,
		PaymentSourceTypeAlipay,
	}
}

type Payment struct {
	Source *struct {
		Type *PaymentSourceType `json:"type,omitempty"`
	} `json:"source,omitempty"`
}

type Choice = SourceType

type SourceTypeAlipay struct {
	DataString          *string `json:"data_string,omitempty"`
	NativeURL           *string `json:"native_url,omitempty"`
	StatementDescriptor *string `json:"statement_descriptor,omitempty"`
}
