// Code generated by oapi-codegen. DO NOT EDIT.

package slicespointer

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Payments []string

func (p Payments) Validate() error {
	if p == nil {
		return nil
	}
	if len(p) < 1 {
		return runtime.NewValidationError("", fmt.Sprintf("must have at least 1 items, got %d", len(p)))
	}
	for i, item := range p {
		if err := schemaTypesValidate.Var(item, "omitempty,min=3"); err != nil {
			return runtime.NewValidationErrorFromError(fmt.Sprintf("[%d]", i), err)
		}
	}
	return nil
}

type Data map[string]any

func (d Data) Validate() error {
	return nil
}

type User struct {
	Payments Payments       `json:"payments,omitempty"`
	Data     Data           `json:"data,omitempty"`
	Prefs    []string       `json:"prefs,omitempty"`
	Address  map[string]any `json:"address,omitempty"`
}

func (u User) Validate() error {
	if v, ok := any(u.Payments).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			return runtime.NewValidationErrorFromError("Payments", err)
		}
	}
	if v, ok := any(u.Data).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			return runtime.NewValidationErrorFromError("Data", err)
		}
	}
	return nil
}
