// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type CreateTestBody struct {
	ID     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

type GetBaseResponse struct {
	Items *GetBase_Response_Items `json:"items,omitempty"`
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type GetBase_Response_Items []GetBase_Response_Items_Item

type GetBase_Response_Items_Item struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}
