// Code generated by oapi-codegen. DO NOT EDIT.

package example2

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type CreateOrderBody struct {
	UserID     *string     `json:"user_id,omitempty"`
	ClientType *ClientType `json:"client_type,omitempty"`
}

func (c CreateOrderBody) Validate() error {
	if c.ClientType != nil {
		if v, ok := any(c.ClientType).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("ClientType", err)
			}
		}
	}
	return nil
}
