// Code generated by oapi-codegen. DO NOT EDIT.

package example2

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type ClientType struct {
	Name    string          `json:"name" validate:"required"`
	Address *Address        `json:"address,omitempty"`
	Type    *ClientTypeType `json:"type,omitempty"`
}

func (c ClientType) Validate() error {
	if err := schemaTypesValidate.Var(c.Name, "required"); err != nil {
		return runtime.NewValidationErrorFromError("Name", err)
	}
	if c.Address != nil {
		if v, ok := any(c.Address).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Address", err)
			}
		}
	}
	if c.Type != nil {
		if v, ok := any(c.Type).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Type", err)
			}
		}
	}
	return nil
}

type Address struct {
	Street string `json:"street" validate:"required"`
	City   string `json:"city" validate:"required"`
	Zip    string `json:"zip" validate:"required"`
}

func (a Address) Validate() error {
	return schemaTypesValidate.Struct(a)
}
