// Code generated by oapi-codegen. DO NOT EDIT.

package multiple

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type CreateBookingBody = Booking
