// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type PostFooBody = string

type PostFooResponse = string

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Order struct {
	Client       *Identity         `json:"client,omitempty"`
	Verification *Verification     `json:"verification,omitempty"`
	Other        map[string]string `json:"other,omitempty"`
}

func (o Order) Validate() error {
	if o.Client != nil {
		if v, ok := any(o.Client).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Client", err)
			}
		}
	}
	if o.Verification != nil {
		if v, ok := any(o.Verification).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Verification", err)
			}
		}
	}
	return nil
}

type Identity struct {
	Issuer string `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	return schemaTypesValidate.Struct(i)
}

type Verification struct {
	Verifier *Address `json:"verifier,omitempty"`
}

func (v Verification) Validate() error {
	if v.Verifier != nil {
		if v, ok := any(v.Verifier).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Verifier", err)
			}
		}
	}
	return nil
}

type Address struct {
	City     *string   `json:"city,omitempty"`
	Location *Location `json:"location,omitempty"`
}

func (a Address) Validate() error {
	if a.Location != nil {
		if v, ok := any(a.Location).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Location", err)
			}
		}
	}
	return nil
}

type Location struct {
	Description *string `json:"description,omitempty"`
}

func (l Location) Validate() error {
	return schemaTypesValidate.Struct(l)
}
