openapi: 3.0.0
info:
  title: Any Type Response Example
  version: 1.0.0
paths:
  /empty-schema:
    get:
      summary: Response with empty schema (becomes any with =)
      operationId: getEmptySchema
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: {}

  /no-type:
    get:
      summary: Response with no type specified (becomes any with =)
      operationId: getNoType
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                description: A schema with no type

  /malformed-like-ledger:
    get:
      summary: Malformed response like ledger.yml (becomes any without =)
      operationId: getMalformed
      responses:
        '200':
          description: Success
          content:
            application/json:
              type: array
              items:
                type: string

  /explicit-object:
    get:
      summary: Response with explicit object type
      operationId: getExplicitObject
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  data:
                    description: Field with no type (becomes any)

components:
  schemas:
    EmptySchema:
      description: Empty schema becomes any

    NoTypeSchema:
      description: Schema with no type
      properties:
        field1:
          type: string

    MixedSchema:
      type: object
      properties:
        normalField:
          type: string
        anyField:
          description: This has no type

