// Code generated by oapi-codegen. DO NOT EDIT.

package anytype

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var responseTypesValidate *validator.Validate

func init() {
	responseTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(responseTypesValidate)
}

type GetEmptySchemaResponse = any

// GetNoTypeResponse A schema with no type
type GetNoTypeResponse = any

type GetMalformedResponse any

type GetExplicitObjectResponse struct {
	ID *string `json:"id,omitempty"`

	// Data Field with no type (becomes any)
	Data *any `json:"data,omitempty"`
}

func (g GetExplicitObjectResponse) Validate() error {
	if g.Data != nil {
		if v, ok := any(g.Data).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("Data", err)
			}
		}
	}
	return nil
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

// EmptySchema Empty schema becomes any
type EmptySchema = any

// NoTypeSchema Schema with no type
type NoTypeSchema struct {
	Field1 *string `json:"field1,omitempty"`
}

func (n NoTypeSchema) Validate() error {
	return schemaTypesValidate.Struct(n)
}

type MixedSchema struct {
	NormalField *string `json:"normalField,omitempty"`

	// AnyField This has no type
	AnyField *any `json:"anyField,omitempty"`
}

func (m MixedSchema) Validate() error {
	if m.AnyField != nil {
		if v, ok := any(m.AnyField).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				return runtime.NewValidationErrorFromError("AnyField", err)
			}
		}
	}
	return nil
}
