openapi: "3.0.0"
info:
  version: 1.0.0
  title: Nullable Union Example
  description: Example of anyOf/oneOf with null being treated as optional properties
paths:
  /users:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        # anyOf with string and null - should become *string
        name:
          anyOf:
            - type: string
            - type: "null"
        # oneOf with integer and null - should become *int
        age:
          oneOf:
            - type: integer
            - type: "null"
        # anyOf with ref and null - should become *Address
        address:
          anyOf:
            - $ref: '#/components/schemas/Address'
            - type: "null"
        # oneOf with ref and null (null first) - should become *Contact
        contact:
          oneOf:
            - type: "null"
            - $ref: '#/components/schemas/Contact'
        # Regular property for comparison
        id:
          type: string

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        # Nested nullable union
        zipCode:
          anyOf:
            - type: string
            - type: "null"

    Contact:
      type: object
      properties:
        email:
          type: string
        phone:
          oneOf:
            - type: string
            - type: "null"
