// Code generated by oapi-codegen. DO NOT EDIT.

package simple

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type PostUsersBody = User

var responseTypesValidate *validator.Validate

func init() {
	responseTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(responseTypesValidate)
}

type PostUsersResponse struct {
	Name string `json:"name" validate:"required"`

	// Active Whether the user is active
	Active bool `json:"active"`

	// Verified Optional boolean field
	Verified *bool `json:"verified,omitempty"`
}

func (p PostUsersResponse) Validate() error {
	if err := responseTypesValidate.Struct(p); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type User struct {
	Name string `json:"name" validate:"required"`

	// Active Whether the user is active
	Active bool `json:"active"`

	// Verified Optional boolean field
	Verified *bool `json:"verified,omitempty"`
}

func (u User) Validate() error {
	if err := schemaTypesValidate.Struct(u); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}
