openapi: "3.0.0"
info:
  version: 1.0.0
  title: Generate models
paths:
  /client:
    get:
      operationId: getClient
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
    put:
      operationId: updateClient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  details:
                    type: string
                  data:
                    type: object
                    properties:
                      code:
                        type: string
                        description: "Error code"
                      message:
                        type: string
                        description: "Error message"
                required:
                - code
components:
  schemas:
    Person:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        age:
          type: integer
        address:
          type: string
        mother:
          $ref: "#/components/schemas/Person"
        father:
          $ref: "#/components/schemas/Person"
    # NOTE that this is not generated by default because it's not referenced.
    # If you want it, you need to use the following YAML configuration:
    #
    # skip-prune: true
    Unreferenced:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
