// Code generated by oapi-codegen. DO NOT EDIT.

package inlinesametype

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var queryTypesValidate *validator.Validate

func init() {
	queryTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(queryTypesValidate)
}

type SearchQuery struct {
	// Filter Filter results (first definition - optional, minLength 1)
	Filter *string `json:"filter,omitempty" validate:"omitempty,min=1"`
	Limit  *int    `json:"limit,omitempty"`
}

func (s SearchQuery) Validate() error {
	return queryTypesValidate.Struct(s)
}

type SearchResponse struct {
	Results []string `json:"results,omitempty"`
}
