// Code generated by oapi-codegen. DO NOT EDIT.

package xoapicodegenextratags

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Client struct {
	Name string  `json:"name" validate:"required"`
	ID   float32 `json:"id" validate:"required"`
}

func (c Client) Validate() error {
	if err := schemaTypesValidate.Struct(c); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

type ClientWithExtension struct {
	Name string  `json:"name" validate:"required"`
	ID   float32 `gorm:"primarykey" json:"id" safe-to-log:"true" validate:"required,min=1,max=256"`
}

func (c ClientWithExtension) Validate() error {
	if err := schemaTypesValidate.Struct(c); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}
