openapi: "3.0.0"
info:
  version: 1.0.0
  title: Using complex schemas
  description: An example of `anyOf` with extra properties
paths:

components:
  schemas:
    ClientWithExtra:
      anyOf:
        - type: string
        - type: boolean
      additionalProperties:
        properties:
          extra:
            type: string
